<?php
require_once 'DokuModelAdapterTestCase.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-01 at 02:25:01.
 */
class DokuModelAdapterTest extends DokuModelAdapterTestCase{
    
    public function __construct($name="DokuModelAdapterTest") {
        parent::__construct($name);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @test getHtmlPageTest
     */
    public function getHtmlPageTest(){
        $page="prv:unfitxer";
        $id_page= str_replace(":", "_", $page);
        $title= $page;
        try{
            $resp = $this->getDokuModelAdapter()->getHtmlPage($page);
        }catch (PHPUnit_Framework_Exception $e){
            $this->assertFalse(TRUE);
        }
        $this->assertEquals($resp['id'], $id_page);
        $this->assertEquals($resp["ns"], $page);
        $this->assertEquals($resp["title"], $title);
        $this->assertArrayHasKey("content", $resp);
        
        print $resp["content"];
        
    }

}
